// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayCourt.Infrastructure.Data;

#nullable disable

namespace PlayCourt.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PlayCourtDbContext))]
    [Migration("20260521025633_ModelReviewFix")]
    partial class ModelReviewFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayCourt.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Amenities_Name");

                    b.ToTable("Amenities", "dbo");
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerEarnings")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("PlatformFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "UserProfileId")
                        .HasName("UQ_Bookings_Id_UserProfileId");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_Bookings_UserProfileId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CourtId", "EndAt", "Status")
                        .HasDatabaseName("IX_Bookings_CourtId_EndAt_Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("CourtId", "StartAt", "EndAt")
                        .HasDatabaseName("IX_Bookings_Active_Court_Time")
                        .HasFilter("[IsDeleted] = 0 AND [Status] IN (0,1)");

                    b.HasIndex("CourtId", "StartAt", "Status")
                        .HasDatabaseName("IX_Bookings_CourtId_StartAt_Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Bookings", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Bookings_Amounts", "[TotalPrice] >= 0 AND [PlatformFee] >= 0 AND [OwnerEarnings] >= 0");

                            t.HasCheckConstraint("CHK_Bookings_FeeMath", "[TotalPrice] = [PlatformFee] + [OwnerEarnings]");

                            t.HasCheckConstraint("CHK_Bookings_Status", "[Status] IN (0,1,2,3,4)");

                            t.HasCheckConstraint("CHK_Bookings_Time", "[StartAt] < [EndAt]");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint");

                    b.Property<short?>("OldStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("BookingStatusHistories", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_BookingStatusHistories_NewStatus", "[NewStatus] IN (0,1,2,3,4)");

                            t.HasCheckConstraint("CHK_BookingStatusHistories_OldStatus", "[OldStatus] IS NULL OR [OldStatus] IN (0,1,2,3,4)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("Indoor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId")
                        .HasDatabaseName("IX_Courts_SportId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("IX_Courts_VenueId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Courts_VenueId_Name_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Courts", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Courts_Status", "[Status] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.CourtOwnerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLicenseNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<short>("VerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CourtOwnerProfiles_UserProfileId");

                    b.ToTable("CourtOwnerProfiles", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_CourtOwnerProfiles_VerificationStatus", "[VerificationStatus] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.CourtSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "StartAt", "EndAt")
                        .HasDatabaseName("IX_CourtSchedules_CourtId_Time");

                    b.ToTable("CourtSchedules", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_CourtSchedules_Time", "[StartAt] < [EndAt]");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<short>("MaxParticipants")
                        .HasColumnType("smallint");

                    b.Property<short?>("RequiredSkillLevelMax")
                        .HasColumnType("smallint");

                    b.Property<short?>("RequiredSkillLevelMin")
                        .HasColumnType("smallint");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourtId")
                        .HasDatabaseName("IX_Matches_CourtId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("HostId");

                    b.HasIndex("SportId");

                    b.HasIndex("StartAt", "Status", "SportId")
                        .HasDatabaseName("IX_Matches_StartAt_Status_SportId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Matches", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Matches_MaxParticipants", "[MaxParticipants] > 0");

                            t.HasCheckConstraint("CHK_Matches_RequiredSkillLevelMax", "[RequiredSkillLevelMax] IS NULL OR [RequiredSkillLevelMax] IN (0,1,2)");

                            t.HasCheckConstraint("CHK_Matches_RequiredSkillLevelMin", "[RequiredSkillLevelMin] IS NULL OR [RequiredSkillLevelMin] IN (0,1,2)");

                            t.HasCheckConstraint("CHK_Matches_RequiredSkillLevelRange", "[RequiredSkillLevelMin] IS NULL OR [RequiredSkillLevelMax] IS NULL OR [RequiredSkillLevelMin] <= [RequiredSkillLevelMax]");

                            t.HasCheckConstraint("CHK_Matches_Status", "[Status] IN (0,1,2,3)");

                            t.HasCheckConstraint("CHK_Matches_Time", "[StartAt] < [EndAt]");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.MatchInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("InviteeId")
                        .HasColumnType("int");

                    b.Property<int>("InviterId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.HasKey("Id");

                    b.HasIndex("InviteeId");

                    b.HasIndex("InviterId");

                    b.HasIndex("MatchId", "InviteeId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MatchInvitations_Match_Invitee");

                    b.ToTable("MatchInvitations", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_MatchInvitations_Status", "[Status] IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.MatchJoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MatchJoinRequests_PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MatchJoinRequests_MatchId_PlayerId");

                    b.ToTable("MatchJoinRequests", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_MatchJoinRequests_Status", "[Status] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.MatchParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("UX_MatchParticipants_OneHostPerMatch")
                        .HasFilter("[IsHost] = 1");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MatchParticipants_PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MatchParticipants_MatchId_PlayerId");

                    b.ToTable("MatchParticipants", "dbo");
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<short?>("ReferenceType")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Notifications_Type", "[Type] IN (0,1,2,3,4)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_Payments_BookingId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Payments_UserId");

                    b.HasIndex("Provider", "TransactionCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_Provider_TransactionCode")
                        .HasFilter("[TransactionCode] IS NOT NULL");

                    b.ToTable("Payments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Payments_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CHK_Payments_Status", "[Status] IN (0,1,2)");

                            t.HasCheckConstraint("CHK_Payments_Type", "[Type] IN (0,1,2)");

                            t.HasCheckConstraint("CHK_Payments_TypeBookingId", "([Type] = 0 AND [BookingId] IS NOT NULL) OR ([Type] IN (1,2))");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.PlayerSport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<short>("SkillLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId")
                        .HasDatabaseName("IX_PlayerSports_SportId");

                    b.HasIndex("UserProfileId", "SportId")
                        .IsUnique()
                        .HasDatabaseName("UQ_PlayerSports_UserProfileId_SportId");

                    b.ToTable("PlayerSports", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_PlayerSports_SkillLevel", "[SkillLevel] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.PricingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek")
                        .HasDatabaseName("IX_PricingRules_CourtId_DayOfWeek");

                    b.ToTable("PricingRules", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_PricingRules_DayOfWeek", "[DayOfWeek] BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CHK_PricingRules_EffectiveRange", "[EffectiveTo] IS NULL OR [EffectiveFrom] <= [EffectiveTo]");

                            t.HasCheckConstraint("CHK_PricingRules_Price", "[PricePerHour] >= 0");

                            t.HasCheckConstraint("CHK_PricingRules_Time", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Reviews_BookingId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("PlayerId");

                    b.HasIndex("BookingId", "PlayerId");

                    b.ToTable("Reviews", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Reviews_Rating", "[Rating] >= 1 AND [Rating] <= 5 AND ([Rating] * 10) % 5 = 0");

                            t.HasCheckConstraint("CHK_Reviews_Status", "[Status] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<short>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("IX_ReviewImages_ReviewId");

                    b.ToTable("ReviewImages", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_ReviewImages_DisplayOrder", "[DisplayOrder] >= 0");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short?>("PlayerCount")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sports_Code");

                    b.ToTable("Sports", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Sports_PlayerCount", "[PlayerCount] IS NULL OR [PlayerCount] > 0");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Phone_Active")
                        .HasFilter("[Phone] IS NOT NULL AND [IsDeleted] = 0");

                    b.ToTable("Users", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Users_Role", "[Role] IN (0,1,2)");

                            t.HasCheckConstraint("CHK_Users_Status", "[Status] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.UserFavoriteVenue", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("UserProfileId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("UserFavoriteVenues", "dbo");
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<short?>("Gender")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserProfiles_UserId");

                    b.ToTable("UserProfiles", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_UserProfiles_Gender", "[Gender] IS NULL OR [Gender] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("CourtOwnerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time(0)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CourtOwnerProfileId")
                        .HasDatabaseName("IX_Venues_CourtOwnerProfileId")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Venues", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_Venues_Latitude", "[Latitude] IS NULL OR ([Latitude] >= -90 AND [Latitude] <= 90)");

                            t.HasCheckConstraint("CHK_Venues_Longitude", "[Longitude] IS NULL OR ([Longitude] >= -180 AND [Longitude] <= 180)");

                            t.HasCheckConstraint("CHK_Venues_Status", "[Status] IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueAmenity", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("VenueId", "AmenityId")
                        .HasName("PK_VenueAmenities");

                    b.HasIndex("AmenityId");

                    b.ToTable("VenueAmenities", "dbo");
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId")
                        .IsUnique()
                        .HasDatabaseName("UX_VenueImages_OneCoverPerVenue")
                        .HasFilter("[IsCover] = 1");

                    b.ToTable("VenueImages", "dbo");
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueOpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("UQ_VenueOpeningHours_Venue_Day");

                    b.ToTable("VenueOpeningHours", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_VenueOpeningHours_Day", "[DayOfWeek] BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CHK_VenueOpeningHours_Time", "[IsClosed] = 1 OR ([OpenTime] IS NOT NULL AND [CloseTime] IS NOT NULL AND [OpenTime] < [CloseTime])");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_VenueStaffs_VenueId_UserId");

                    b.ToTable("VenueStaffs", "dbo", t =>
                        {
                            t.HasCheckConstraint("CHK_VenueStaffs_Role", "[Role] IN (0,1,2)");
                        });
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Booking", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Court", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.CourtOwnerProfile", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithOne()
                        .HasForeignKey("PlayCourt.Domain.Entities.CourtOwnerProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.CourtSchedule", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Match", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.MatchInvitation", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.MatchJoinRequest", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.MatchParticipant", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlayCourt.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.PlayerSport", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.PricingRule", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Review", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId", "PlayerId")
                        .HasPrincipalKey("Id", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Booking_Player");
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.ReviewImage", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Review", null)
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.UserFavoriteVenue", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("PlayCourt.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.Venue", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.CourtOwnerProfile", null)
                        .WithMany()
                        .HasForeignKey("CourtOwnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueAmenity", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueImage", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueOpeningHour", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayCourt.Domain.Entities.VenueStaff", b =>
                {
                    b.HasOne("PlayCourt.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlayCourt.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
